<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5IBKFPL" ignored="0" name="Test" tests="3" failures="2" timestamp="06 Oct 2020 04:32:49 GMT" time="85.014" errors="0">
  <testcase name="mapTest" time="16.793" classname="com.testData.TestCaseForScenarios">
    <failure type="java.lang.AssertionError" message="expected [Stadium] but found [Wankhede Stadium]">
      <![CDATA[java.lang.AssertionError: expected [Stadium] but found [Wankhede Stadium]
	at com.testData.TestCaseForScenarios.mapTest(TestCaseForScenarios.java:65)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- mapTest -->
  <testcase name="qaagility" time="46.697" classname="com.testData.TestCaseForScenarios"/>
  <testcase name="superSmartCalculator" time="21.495" classname="com.testData.TestCaseForScenarios">
    <failure type="java.lang.AssertionError" message="expected [-34] but found [9]">
      <![CDATA[java.lang.AssertionError: expected [-34] but found [9]
	at com.testData.TestCaseForScenarios.superSmartCalculator(TestCaseForScenarios.java:115)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- superSmartCalculator -->
</testsuite> <!-- Test -->
